(cl:in-package gesture-msg)
(cl:export '(GESTURE0-VAL
          GESTURE0
          GESTURE1-VAL
          GESTURE1
          GESTURE2-VAL
          GESTURE2
          GESTURE3-VAL
          GESTURE3
          GESTURE4-VAL
          GESTURE4
          GESTURE5-VAL
          GESTURE5
          GESTURE6-VAL
          GESTURE6
          GESTURE7-VAL
          GESTURE7
          GESTURE8-VAL
          GESTURE8
          GESTURE9-VAL
          GESTURE9
          GESTURE10-VAL
          GESTURE10
          GESTURE11-VAL
          GESTURE11
          GESTURE12-VAL
          GESTURE12
          GESTURE13-VAL
          GESTURE13
          GESTURE14-VAL
          GESTURE14
          GESTURE15-VAL
          GESTURE15
          GESTURE16-VAL
          GESTURE16
          GESTURE17-VAL
          GESTURE17
          GESTURE18-VAL
          GESTURE18
          GESTURE19-VAL
          GESTURE19
))