(cl:in-package body_msgs-msg)
(cl:export '(PLAYERID-VAL
          PLAYERID
          HEAD-VAL
          HEAD
          NECK-VAL
          NECK
          RIGHT_HAND-VAL
          RIGHT_HAND
          LEFT_HAND-VAL
          LEFT_HAND
          RIGHT_SHOULDER-VAL
          RIGHT_SHOULDER
          LEFT_SHOULDER-VAL
          LEFT_SHOULDER
          RIGHT_ELBOW-VAL
          RIGHT_ELBOW
          LEFT_ELBOW-VAL
          LEFT_ELBOW
          TORSO-VAL
          TORSO
          LEFT_HIP-VAL
          LEFT_HIP
          RIGHT_HIP-VAL
          RIGHT_HIP
          LEFT_KNEE-VAL
          LEFT_KNEE
          RIGHT_KNEE-VAL
          RIGHT_KNEE
          LEFT_FOOT-VAL
          LEFT_FOOT
          RIGHT_FOOT-VAL
          RIGHT_FOOT
))