"""autogenerated by genmsg_py from HandPos.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg

class HandPos(roslib.message.Message):
  _md5sum = "33cd725b752112008f3a4635435ee4fb"
  _type = "gesture/HandPos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point left_position
geometry_msgs/Point right_position
bool left_click
bool right_click

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['left_position','right_position','left_click','right_click']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       left_position,right_position,left_click,right_click
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(HandPos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_position is None:
        self.left_position = geometry_msgs.msg.Point()
      if self.right_position is None:
        self.right_position = geometry_msgs.msg.Point()
      if self.left_click is None:
        self.left_click = False
      if self.right_click is None:
        self.right_click = False
    else:
      self.left_position = geometry_msgs.msg.Point()
      self.right_position = geometry_msgs.msg.Point()
      self.left_click = False
      self.right_click = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6d2B.pack(_x.left_position.x, _x.left_position.y, _x.left_position.z, _x.right_position.x, _x.right_position.y, _x.right_position.z, _x.left_click, _x.right_click))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.left_position is None:
        self.left_position = geometry_msgs.msg.Point()
      if self.right_position is None:
        self.right_position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 50
      (_x.left_position.x, _x.left_position.y, _x.left_position.z, _x.right_position.x, _x.right_position.y, _x.right_position.z, _x.left_click, _x.right_click,) = _struct_6d2B.unpack(str[start:end])
      self.left_click = bool(self.left_click)
      self.right_click = bool(self.right_click)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6d2B.pack(_x.left_position.x, _x.left_position.y, _x.left_position.z, _x.right_position.x, _x.right_position.y, _x.right_position.z, _x.left_click, _x.right_click))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.left_position is None:
        self.left_position = geometry_msgs.msg.Point()
      if self.right_position is None:
        self.right_position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 50
      (_x.left_position.x, _x.left_position.y, _x.left_position.z, _x.right_position.x, _x.right_position.y, _x.right_position.z, _x.left_click, _x.right_click,) = _struct_6d2B.unpack(str[start:end])
      self.left_click = bool(self.left_click)
      self.right_click = bool(self.right_click)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6d2B = struct.Struct("<6d2B")
